### PR TITLE
Fix typedef error: (Duration) => void is not a subtype of (dynamic) => void

### PR DESCRIPTION
**Pull request by NBTX**
Sorry about the rubbish commit descriptions, I was just playing around in the hopes I could get it working.

### CODE REVIEW

**Comment by stevenroose** [comment]
Could you perhaps make it into a single commit and not update the pubspec? Also, I don't understand how what you changed makes a difference, isn't it `(Duration) => void` in both cases?

Thanks for the contribution, btw! Good to see some usage!

**Comment by NBTX** [comment]
I thought I'd get that. Sure thing.

I thought so but changing the type definition to include a variable name in the parameter seemed to fix the problem.

**Comment by stevenroose** [comment]
Well if it helps your cause, I'm happy to accept it after you handled the nit ;)

**Comment by NBTX** [comment]
Removed the other commits 😛 
Thanks

**Comment by stevenroose** [comment]
I'm not sure anymore how it works in the case of a [broadcast stream(https://github.com/stevenroose/dart-eventsource/blob/master/lib/eventsource.dart#L47), but I think when you call `listen()` and then `cancel()` the subscription object, the stream will be closed and that will ripple up to the [HTTP stream that we are transforming](https://github.com/stevenroose/dart-eventsource/blob/master/lib/eventsource.dart#L97).

But in all honesty, it's been years since I looked decently at any Dart code.

**Comment by stevenroose** [comment]
Thanks for the fix, btw.

**Pull request merged**
